name: Generate Themes

on:
  schedule:
    - cron: "0 22 * * 0"
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/gen-themes.yml"

jobs:
  gen-themes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v5

      - uses: taiki-e/install-action@just

      - name: Install Neovim
        run: |
          sudo add-apt-repository ppa:neovim-ppa/unstable -y
          sudo apt-get update
          sudo apt-get install -y lua5.4 neovim

      - name: gen-themes
        run: echo "y" | just gen-themes

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.CI_TOKEN }}
          add-paths: |
            themes
          commit-message: "chore: generate themes"
          title: "chore: generate themes"
          body: |
            Automated PR to generate themes.

            This PR was created automatically by the gen-themes workflow.
          branch: gen-themes
          delete-branch: true
          base: main
