name: Generate Samples

on:
  workflow_run:
    workflows: [Update Languages, Generate CSS]
    types:
      - completed
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/gen_samples.yml"

jobs:
  gen-samples:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: taiki-e/install-action@just

      - name: gen-samples
        run: echo "y" | just gen-samples

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.CI_TOKEN }}
          add-paths: |
            samples
          commit-message: "chore: generate samples"
          title: "chore: generate samples"
          body: |
            Automated PR to generate samples.

            This PR was created automatically by the gen-samples workflow.
          branch: gen-samples
          delete-branch: true
          base: main
