name: Generate CSS

on:
  workflow_run:
    workflows: [Generate Themes]
    types:
      - completed
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/gen_css.yml"

jobs:
  gen-css:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: taiki-e/install-action@just

      - name: Install Neovim
        run: |
          sudo add-apt-repository ppa:neovim-ppa/unstable -y
          sudo apt-get update
          sudo apt-get install -y lua5.4 neovim

      - name: gen-css
        run: echo "y" | just gen-css

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.CI_TOKEN }}
          add-paths: |
            css
          commit-message: "chore: generate css"
          title: "chore: generate css"
          body: |
            Automated PR to generate css.

            This PR was created automatically by the gen-css workflow.
          branch: gen-css
          delete-branch: true
          base: main
