name: Rust CI

on:
  push:
    branches: [ main ]
    paths:
      - "crates/**"
      - ".github/workflows/rust.yml"
  pull_request:
    paths:
      - "crates/**"
      - ".github/workflows/rust.yml"
  workflow_dispatch:

jobs:
  test:
    uses: leandrocp/github-actions/.github/workflows/rust-test.yml@main
    with:
      msrv: '1.91'
      manifest-path: 'crates/lumis/Cargo.toml'
  lint:
    uses: leandrocp/github-actions/.github/workflows/rust-lint.yml@main
    with:
      msrv: '1.91'
      manifest-path: 'crates/lumis/Cargo.toml'
