name: Update Parsers

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/update_parsers.yml"

jobs:
  update-parsers:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v5

      - uses: taiki-e/install-action@just

      - name: update-parsers
        run: echo "y" | just update-parsers

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: update parsers"
          title: "chore: update parsers"
          body: |
            Automated PR to update parsers.

            This PR was created automatically by the update-parsers workflow.
          branch: update-parsers
          delete-branch: true
          base: main
