name: Update Queries

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/update_queries.yml"

jobs:
  update-queries:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v5

      - uses: taiki-e/install-action@just

      - name: update-queries
        run: echo "y" | just update-queries

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: update queries"
          title: "chore: update queries"
          body: |
            Automated PR to update queries.

            This PR was created automatically by the update-queries workflow.
          branch: update-queries
          delete-branch: true
          base: main
