name: Update Languages

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/update_langs.yml"

jobs:
  update-parsers:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v5

      - uses: leafo/gh-actions-lua@v11

      - uses: taiki-e/install-action@just

      - name: update-parsers
        run: echo "y" | just update-parsers

      - name: update-queries
        run: echo "y" | just update-queries

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.CI_TOKEN }}
          add-paths: |
            vendored_parsers
            queries
          commit-message: "chore: update langs"
          title: "chore: update langs"
          body: |
            Automated PR to update parsers and queries.

            This PR was created automatically by the update-langs workflow.
          branch: update-langs
          delete-branch: true
          base: main
