name: Update Languages

on:
  schedule:
    - cron: "0 22 * * 0"
  workflow_dispatch:
  push:
    tags-ignore:
      - "**"
    paths:
      - ".github/workflows/update-langs.yml"

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      languages: ${{ steps.set-matrix.outputs.languages }}
    steps:
      - uses: actions/checkout@v6

      - name: Generate language matrix
        id: set-matrix
        run: |
          LANGS=$(cargo metadata --format-version 1 --no-deps \
            | jq -c '.packages[] | select(.name == "lumis") | .metadata.langs.parsers | to_entries | map(select(.value.git)) | map(.key)')
          echo "Generated matrix for languages: $LANGS"
          echo "languages=$LANGS" >> $GITHUB_OUTPUT

  update-parsers:
    needs: generate-matrix
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        language: ${{ fromJson(needs.generate-matrix.outputs.languages) }}

    steps:
      - uses: actions/checkout@v6

      - uses: taiki-e/install-action@just

      - uses: leafo/gh-actions-lua@v12

      - uses: leafo/gh-actions-luarocks@v5

      - name: Install Lua dependencies
        run: luarocks install toml-edit && luarocks install dkjson

      - name: langs-get-parsers for ${{ matrix.language }}
        run: just langs-get-parsers ${{ matrix.language }}

      - name: langs-get-queries for ${{ matrix.language }}
        run: just langs-get-queries ${{ matrix.language }}

      - name: docs-gen-languages
        run: just docs-gen-languages

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.CI_TOKEN }}
          add-paths: |
            crates/lumis/Cargo.toml
            crates/lumis/vendored_parsers
            crates/lumis/queries
            LANGUAGES.md
          commit-message: "chore: update ${{ matrix.language }}"
          title: "chore: update ${{ matrix.language }}"
          body: |
            Automated PR to update parser and queries for **${{ matrix.language }}**.

            This PR was created automatically by the update-langs workflow.
          branch: update-langs-${{ matrix.language }}
          delete-branch: true
          base: main
