name: Update Languages

on:
  schedule:
    - cron: "0 22 * * 0"
  workflow_dispatch:
  push:
    tags-ignore:
      - "**"
    paths:
      - ".github/workflows/update-langs.yml"

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      languages: ${{ steps.set-matrix.outputs.languages }}
    steps:
      - uses: actions/checkout@v6

      - uses: leafo/gh-actions-lua@v12

      - uses: taiki-e/install-action@just

      - name: Generate language matrix
        id: set-matrix
        run: |
          LANGS=$(just list-vendored-parsers | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "Generated matrix for languages: $LANGS"
          echo "languages=$LANGS" >> $GITHUB_OUTPUT

  update-parsers:
    needs: generate-matrix
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        language: ${{ fromJson(needs.generate-matrix.outputs.languages) }}

    steps:
      - uses: actions/checkout@v6

      - uses: leafo/gh-actions-lua@v12

      - uses: taiki-e/install-action@just

      - name: update-parsers for ${{ matrix.language }}
        run: echo "y" | just update-vendored-parsers ${{ matrix.language }}

      - name: update-queries for ${{ matrix.language }}
        run: echo "y" | just update-queries ${{ matrix.language }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.CI_TOKEN }}
          add-paths: |
            crates/lumis/vendored_parsers
            crates/lumis/queries
          commit-message: "chore: update ${{ matrix.language }}"
          title: "chore: update ${{ matrix.language }}"
          body: |
            Automated PR to update parser and queries for **${{ matrix.language }}**.

            This PR was created automatically by the update-langs workflow.
          branch: update-langs-${{ matrix.language }}
          delete-branch: true
          base: main
